name: nulis_app
description: Aplikasi catatan Markdown pribadi — dikonversi dari Kotlin ke Flutter.
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  # === State Management ===
  flutter_riverpod: ^3.3.1
  riverpod_annotation: ^4.0.2

  # === Database (pengganti Room) ===
  drift: ^2.32.1
  drift_flutter: ^0.3.0
  sqlite3_flutter_libs: ^0.6.0

  # === Preferences (pengganti DataStore + SharedPrefs) ===
  shared_preferences: ^2.3.5

  # === Markdown (pengganti Markwon) ===
  flutter_markdown: ^0.7.3
  markdown: ^7.2.2

  # === Google Drive & Auth ===
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  http: ^1.3.0

  # === Biometric ===
  local_auth: ^3.0.1

  # === Navigasi ===
  go_router: ^17.2.0

  # === Image ===
  cached_network_image: ^3.4.1

  # === Utils ===
  uuid: ^4.5.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1
  share_plus: ^12.0.2
  file_picker: ^8.0.7

  # === Export PDF ===
  printing: ^5.13.2
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.32.1
  build_runner: ^2.4.13
  riverpod_generator: ^4.0.3
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.3

dependency_overrides:
  analyzer: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
